#include <iostream>
using namespace std;

// Fibonacchi is a series of numbers starts from 1 then new number generated by adding first previous number and second previous number

void PrintFibonacciNum(int Length)
{
    int Prev1 = 1, Prev2 = 0, FibNum = 0;
    cout << "1   ";  // always start with 1 then start calculating Fibonacci number

    for (int i = 1; i < Length; i++)
    {
        FibNum = Prev1 + Prev2;
        cout << FibNum << "   ";
        Prev2 = Prev1;
        Prev1 = FibNum;
    }
}

int main()
{
    
    PrintFibonacciNum(10);


    return 0;
}

