using System;
using System.Threading;
using System.Threading.Tasks;

/* =================================================================================
 * [LESSON PART 2: COOPERATIVE CANCELLATION]
 * 
 * CONCEPT: "Cooperative Cancellation" & The Observer Mechanism
 * 
 * 1. THE PROBLEM (Why it exists):
 * 
 *    Imagine a user starts downloading a massive 5GB file over a slow network. 
 *    Halfway through, they click "Cancel" or close the window. 
 *    - Without cancellation, the server and network keep downloading that file anyway, 
 *      wasting precious CPU, memory, and bandwidth.
 *      
 *    - Forcefully killing the thread from the outside (like the old Thread.Abort) 
 *      is highly dangerous. It leaves files corrupted on the disk, leaks memory, 
 *      and crashes applications.
 * 
 * 
 * 2. THE SOLUTION: Cooperative Cancellation
 * 
 *    Instead of murdering the task from the outside, we use a "cooperative" approach. 
 *    The caller and the background download task work together as a team. 
 *    
 *    - The caller provides a signal flag.
 *    - The background task checks this flag at safe intervals. If signaled, the 
 *      task gracefully stops itself, closes the file stream safely, and exits.
 * 
 * 
 * 3. THE TWO PLAYERS (The Observer Pattern):
 * 
 *    - CancellationTokenSource (CTS): The Instigator / Owner. 
 *      This is the object that instantiates the process. It holds the trigger. 
 *      When a user clicks "Cancel", the CTS calls its '.Cancel()' method.
 *      
 *    - CancellationToken: The Listener / Observer. 
 *      This is a lightweight, read-only structure generated by the CTS and passed 
 *      down the river. It cannot trigger cancellation; it can only watch it.
 * 
 * 
 * 4. HOW THE TASK OBSERVES THE TOKEN:
 * 
 *    Asynchronous methods "observe" the token in two distinct ways:
 *    A. Active Polling: Inside a loop (like reading file chunks), your code manually 
 *       checks 'token.ThrowIfCancellationRequested()'. If the CTS called '.Cancel()', 
 *       this line instantly throws an 'OperationCanceledException'.
 *       
 *    B. Reactive Callbacks: Downstream APIs (like HttpClient or Stream.WriteAsync) 
 *       register a listener hook directly inside the token. The moment '.Cancel()' 
 *       is called, the token flashes a signal, waking up blocked or sleeping 
 *       network streams immediately so they don't hang indefinitely.
 * ================================================================================= */

class Program
{
    static async Task Main()
    {
        // 1. Create the source that controls the cancellation signal
        using var cts = new CancellationTokenSource();

        // Simulate a user cancellation action after 1.5 seconds
        _ = Task.Run(async () =>
        {
            await Task.Delay(1500);
            Console.WriteLine("[System] User clicked 'Cancel' button.");

            // Signal cancellation to the token
            await cts.CancelAsync();
        });


        // this try-catch block is just to catch the cancelation command
        try
        {
            // 2. Pass the token down to our asynchronous task
            await ProcessLargeFileAsync(cts.Token);
        }
        catch (OperationCanceledException)
        {
            Console.WriteLine("[System] The process was cleanly cancelled and resources were freed.");
        }
    }

    static async Task ProcessLargeFileAsync(CancellationToken cancellationToken)
    {
        for (int i = 1; i <= 5; i++)
        {
            // 3. Cooperatively check the token before starting heavy work
            cancellationToken.ThrowIfCancellationRequested();

            Console.WriteLine($"Processing chunk {i}/5...");

            // 4. Pass the token to downstream asynchronous APIs (e.g., Task.Delay, HttpClient, EF Core)
            await Task.Delay(1000, cancellationToken);
        }

        /* 
          [THE "DOWNSTREAM" FLOW]
          
          CONCEPT: "Passing the Token Downstream"
          
          1. THE ANALOGY:
             Think of your code execution like a flowing river. 
             - The entry point or parent method you write is "Upstream" (the source).
             - Any async methods you call inside it are "Downstream" (further down the river).
          
          2. THE GOLDEN RULE:
             If your method receives a 'CancellationToken' as a parameter, DO NOT keep it 
             to yourself. You must forward it (pass it along) to every downstream 
             asynchronous operation you invoke inside your method (e.g., Task.Delay, 
             HttpClient, or database queries).
          
          3. WHY THIS IS CRITICAL:
             If you accept a token but call 'await Task.Delay(1000)' without passing it, 
             that delay becomes "deaf" to the cancellation signal. It will force the 
             thread to wait the entire 1000ms even if the user cancelled at millisecond 10.
             By passing the token downstream, the delay wakes up instantly and aborts.
           */
    }
}

